apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: require-matching-service-account
  annotations:
    policies.kyverno.io/title: Require Matching ServiceAccount
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment
spec:
  validationActions:
    - Audit

  evaluation:
    background:
      enabled: true

  matchConstraints:
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments"]

    namespaceSelector:
      matchLabels:
        workload: "true"

  validations:
    - expression: >-
        has(object.spec.template.spec.serviceAccountName)
        &&
        object.spec.template.spec.serviceAccountName != ""
        &&
        object.spec.template.spec.serviceAccountName == object.metadata.name
      message: >-
        Deployment must use a ServiceAccount with the same name
        as the Deployment.