apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: external-postgresql
  namespace: istio-egress
  labels:
    istio.io/use-waypoint: egress-waypoint
spec:
  hosts:
    - external-postgresql
  addresses:
    - 10.0.3.1/32

  ports:
    - number: 5432
      name: tcp-postgresql
      protocol: TCP

  location: MESH_EXTERNAL
  resolution: STATIC

  endpoints:
    - address: 10.0.3.1