apiVersion: v1
kind: Pod
metadata:
  name: curl-sa-order-service
  namespace: app
spec:
  serviceAccountName: order-service
  containers:
  - name: curl
    image: curlimages/curl:8.10.1
    command:
    - sleep
    - "36000"    
  restartPolicy: Never