apiVersion: v1
kind: Pod
metadata:
  name: curl-sa-api-gateway
  namespace: middle
spec:
  serviceAccountName: api-gateway
  containers:
  - name: curl
    image: curlimages/curl:8.10.1
    command:
    - sleep
    - "360000"    
  restartPolicy: Never