apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-addon
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/chungndinh/platform.git
        revision: main
        directories:
          - path: istio/prod/*
  template:
    metadata:
      name: 'istio-{{path.basename}}'
    spec:
      project: workloads

      source:
        repoURL: https://github.com/chungndinh/platform.git
        targetRevision: main
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: argocd

      syncPolicy:
        automated:
          prune: true
          selfHeal: true